
ALTER TABLE certificate_planer_document_revision_state
RENAME CONSTRAINT certificate_planer_document_revision_state_name_unique
TO certificate_planer_document_revision_index_name_unique;

ALTER TABLE certificate_planer_document_revision_state
RENAME CONSTRAINT certificate_planer_document_revision_state_create_uid_fkey
TO certificate_planer_document_revision_index_create_uid_fkey;

ALTER TABLE certificate_planer_document_revision_state
RENAME CONSTRAINT certificate_planer_document_revision_state_pkey
TO certificate_planer_document_revision_index_pkey;

ALTER TABLE certificate_planer_document_revision_state
RENAME CONSTRAINT certificate_planer_document_revision_state_write_uid_fkey
TO certificate_planer_document_revision_index_write_uid_fkey;

ALTER TABLE certificate_planer_document_revision_state
RENAME TO certificate_planer_document_revision_index;

ALTER TABLE certificate_planer_document_revision
RENAME COLUMN state_id TO index_id;
